name: Android Test Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run Gradle assemble (debug github flavor)
      run: ./gradlew :composeApp:assembleGithubDebug --no-daemon --stacktrace

    - name: Set up ADB for device connection
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: google_apis
        arch: x86_64
        emulator-options: -no-window -no-audio
        script: |
          adb devices

    # Optional: install APK on connected device/emulator (comment if not needed)
    - name: Install debug APK on device
      run: |
        adb install -r $(ls -t composeApp/build/outputs/apk/github/debug/*.apk | head -n1)

    # Optional: launch main activity (replace package/activity as needed)
    - name: Launch main Activity
      run: |
        adb shell am start -n me.knighthat.kreate/.MainActivity
