name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Java 21 (Temurin) with Gradle cache
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses (non-interactive)
        shell: bash
        run: |
          set +e
          yes | sdkmanager --licenses >/dev/null 2>&1
          set -e

      - name: Install Android SDK packages
        shell: bash
        run: |
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Show tool versions
        shell: bash
        run: |
          ./gradlew --version
          java -version
          sdkmanager --list | head -n 50 || true

      - name: Build Saavn Android library (release)
        shell: bash
        run: ./gradlew :saavn:assembleRelease --no-daemon

      - name: Build app (GitHub release flavor)
        shell: bash
        run: ./gradlew :composeApp:assembleGithubRelease --no-daemon

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            composeApp/build/outputs/apk/**/release/*.apk
            composeApp/build/outputs/apk/github/release/*.apk
          if-no-files-found: warn
